version: '3.8'

services:
  mptopup-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mptopup_production
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
